silver_augments = {
    'afk':                  0,
    'band_of_thieves':      0,
    'battlemage':           [30, 15],
    'big_friend':           0,
    'built_different':      0,
    'celestial_blessing':   0,
    'consistency':          0,
    'cybernetic_implants':  0,
    'cybernetic_shell':     0,
    'cybernetic_uplink':    0,
    'double_trouble':       0,
    'electrocharge':        0,
    'exiles':               0,
    'featherweights':       0,
    'first_aid_kit':        0,
    'future_sight':         0,
    'item_grab_bag':        0,
    'knifes_edge':          0,
    'lategame_specialist':  0,
    'ludens_echo':          0,
    'makeshift_armor':      0,
    'pandoras_bench':       0,
    'pandoras_items':       0,
    'preparation':          0,
    'recombobulator':       0,
    'second_wind':          0,
    'stand_united':         0,
    'thrill_of_the_hunt':   0,
    'tiny_titans':          0,
    'tri_force':            0
}

gold_augments = {
    'ancient_archives':     0,
    'ascension':            0,
    'axiom_arc':            0,
    'battlemage':           [45, 20],
    'big_friend':           0,
    'blue_battery':         0,
    'built_different':      0,
    'calculated_loss':      0,
    'celestial_blessing':   0,
    'clear_mind':           0,
    'cluttered_mind':       0,
    'combat_training':      0,
    'component_grab_bag':   0,
    'cybernetic_implants':  0,
    'cybernetic_shell':     0,
    'cybernetic_uplink':    0,
    'double_trouble':       0,
    'electrocharge':        0,
    'exiles':               0,
    'featherweights':       0,
    'first_aid_kit':        0,
    'hustler':              0,
    'jeweled_lotus':        0,
    'knifes_edge':          0,
    'last_stand':           0,
    'ludens_echo':          0,
    'makeshift_armor':      0,
    'metabolic_accelerator':0,
    'phony_frontline':      0,
    'portable_forge':       0,
    'preparation':          0,
    'rich_get_richer':      0,
    'salvage_bin':          0,
    'scoped_weapons':       0,
    'second_wind':          0,
    'stand_united':         0,
    'sunfire_board':        0,
    'threes_company':       0,
    'thrill_of_the_hunt':   0,
    'tri_force':            0,
    'true_twos':            0
}

prismatic_augments = {
    'ancient_archives':     0,
    'band_of_thieves':      0,
    'battlemage':           0,
    'binary_airdrop':       0,
    'birthday_present':     0,
    'built_different':      0,
    'celestial_blessing':   0,
    'cruel_pact':           0,
    'cursed_crown':         0,
    'cybernetic_implants':  0,
    'cybernetic_shell':     0,
    'cybernetic_uplink':    0,
    'double_trouble':       0,
    'electrocharge':        0,
    'featherweights':       0,
    'future_sight':         0,
    'golden_ticket':        0,
    'high_end_shopping':    0,
    'high_roller':          0,
    'item_grab_bag':        0,
    'knifes_edge':          0,
    'level_up':             0,
    'living_forge':         0,
    'lucky_gloves':         0,
    'ludens_echo':          0,
    'march_of_progress':    0,
    'new_recruit':          0,
    'preparation':          0,
    'radiant_relics':       0,
    'stand_united':         0,
    'the_golden_egg':       0,
    'urfs_grab_bag':        0,
    'verdant_veil':         0,
    'windfall':             0,
    'wise_spending':        0,
    'woodland_charm':       0
}
